### ISSUE TITLE
The engine is not freed when selecting another script

### ISSUE THREAD

**Issue by xmacex** [dzautner/13-angels#2]
The SuperCollider engine is not freed, and does not stop when selection to another script.

![](https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzFmZTVmNDljMzU0MTc4NzE1ZF82MDExMTI2MTQ2XzhmZDRjZWRhOTJfei5qcGciXSxbInAiLCJ0aHVtYiIsIngzOTA-Il0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDgxIC1hdXRvLW9yaWVudCJdXQ/6011126146_8fd4ceda92_z.jpg)

This is, in some interesting way, appropriate conceptually as these angels stay around and haunt us from the past, from beyond. Is this on purpose? If yes, I respect it. If not, I think I have a fix for it just a sec.

**Comment by dzautner** [comment]
Nothing is ever accidental with those angels. I am under their complete control at this point. (send help).
